LOCAL_PATH  := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := icuuc51
LOCAL_CFLAGS += -D_REENTRANT -DU_COMMON_IMPLEMENTATION -DU_HAVE_NL_LANGINFO_CODESET=0 -DU_TIMEZONE=timezone -frtti -fno-exceptions -O3 -fvisibility=hidden -DPIC -fPIC
LOCAL_C_INCLUDES := $(LOCAL_PATH)/common $(LOCAL_PATH)/i18n
LOCAL_LDLIBS := -ldl -lm
LOCAL_RTTI_FLAG := -frtti
LOCAL_SHARED_LIBRARIES += libgabi++ libdl
LOCAL_SRC_FILES :=  common/errorcode.cpp \
                    common/putil.cpp \
   					common/umath.c \
   					common/utypes.c \
   					common/uinvchar.c \
                    common/umutex.cpp \
   					common/ucln_cmn.c \
                    common/uinit.c \
                    common/uobject.cpp \
                    common/cmemory.c \
                    common/charstr.cpp \
                    common/udata.cpp \
                    common/ucmndata.c \
                    common/udatamem.c \
                    common/umapfile.c \
                    common/udataswp.c \
                    common/ucol_swp.cpp \
                    common/utrace.c \
                    common/uhash.c \
                    common/uhash_us.cpp \
                    common/uenum.c \
                    common/ustrenum.cpp \
                    common/uvector.cpp \
                    common/ustack.cpp \
                    common/uvectr32.cpp \
                    common/uvectr64.cpp \
                    common/ucnv.c \
                    common/ucnv_bld.cpp \
                    common/ucnv_cnv.c \
                    common/ucnv_io.cpp \
                    common/ucnv_cb.c \
                    common/ucnv_err.c \
                    common/ucnvlat1.c \
                    common/ucnv_u7.c \
                    common/ucnv_u8.c \
                    common/ucnv_u16.c \
                    common/ucnv_u32.c \
                    common/ucnvscsu.c \
                    common/ucnvbocu.cpp \
                    common/ucnv_ext.cpp \
                    common/ucnvmbcs.c \
                    common/ucnv2022.cpp \
                    common/ucnvhz.c \
                    common/ucnv_lmb.c \
                    common/ucnvisci.c \
                    common/ucnvdisp.c \
                    common/ucnv_set.c \
                    common/ucnv_ct.c \
                    common/uresbund.cpp \
                    common/ures_cnv.c \
                    common/uresdata.c \
                    common/resbund.cpp \
                    common/resbund_cnv.cpp \
                    common/messagepattern.cpp \
                    common/ucat.c \
                    common/locmap.c \
                    common/uloc.cpp \
                    common/locid.cpp \
                    common/locutil.cpp \
                    common/locavailable.cpp \
                    common/locdispnames.cpp \
                    common/loclikely.cpp \
                    common/locresdata.cpp \
                    common/bytestream.cpp \
                    common/stringpiece.cpp \
                    common/stringtriebuilder.cpp \
                    common/bytestriebuilder.cpp \
                    common/bytestrie.cpp \
                    common/bytestrieiterator.cpp \
                    common/ucharstrie.cpp \
                    common/ucharstriebuilder.cpp \
                    common/ucharstrieiterator.cpp \
                    common/dictionarydata.cpp \
                    common/appendable.cpp \
                    common/ustr_cnv.c \
                    common/unistr_cnv.cpp \
                    common/unistr.cpp \
                    common/unistr_case.cpp \
                    common/unistr_props.cpp \
                    common/utf_impl.c \
                    common/ustring.cpp \
                    common/ustrcase.cpp \
                    common/ucasemap.cpp \
                    common/ucasemap_titlecase_brkiter.cpp \
                    common/cstring.c \
                    common/ustrfmt.c \
                    common/ustrtrns.cpp \
                    common/ustr_wcs.cpp \
                    common/utext.cpp \
                    common/unistr_case_locale.cpp \
                    common/ustrcase_locale.cpp \
                    common/unistr_titlecase_brkiter.cpp \
                    common/ustr_titlecase_brkiter.cpp \
                    common/normalizer2impl.cpp \
                    common/normalizer2.cpp \
                    common/filterednormalizer2.cpp \
                    common/normlzr.cpp \
                    common/unorm.cpp \
                    common/unormcmp.cpp \
                    common/unorm_it.c \
                    common/chariter.cpp \
                    common/schriter.cpp \
                    common/uchriter.cpp \
                    common/uiter.cpp \
                    common/patternprops.cpp \
                    common/uchar.c \
                    common/uprops.cpp \
                    common/ucase.cpp \
                    common/propname.cpp \
                    common/ubidi_props.c \
                    common/ubidi.c \
                    common/ubidiwrt.c \
                    common/ubidiln.c \
                    common/ushape.cpp \
                    common/uscript.c \
                    common/uscript_props.cpp \
                    common/usc_impl.c \
                    common/unames.cpp \
                    common/utrie.cpp \
                    common/utrie2.cpp \
                    common/utrie2_builder.cpp \
                    common/bmpset.cpp \
                    common/unisetspan.cpp \
                    common/uset_props.cpp \
                    common/uniset_props.cpp \
                    common/uniset_closure.cpp \
                    common/uset.cpp \
                    common/uniset.cpp \
                    common/usetiter.cpp \
                    common/ruleiter.cpp \
                    common/caniter.cpp \
                    common/unifilt.cpp \
                    common/unifunct.cpp \
                    common/uarrsort.c \
                    common/brkiter.cpp \
                    common/ubrk.cpp \
                    common/brkeng.cpp \
                    common/dictbe.cpp \
                    common/rbbi.cpp \
                    common/rbbidata.cpp \
                    common/rbbinode.cpp \
                    common/rbbirb.cpp \
                    common/rbbiscan.cpp \
                    common/rbbisetb.cpp \
                    common/rbbistbl.cpp \
                    common/rbbitblb.cpp \
                    common/serv.cpp \
                    common/servnotf.cpp \
                    common/servls.cpp \
                    common/servlk.cpp \
                    common/servlkf.cpp \
                    common/servrbf.cpp \
                    common/servslkf.cpp \
                    common/uidna.cpp \
                    common/usprep.cpp \
                    common/uts46.cpp \
                    common/punycode.cpp \
                    common/util.cpp \
                    common/util_props.cpp \
                    common/parsepos.cpp \
                    common/locbased.cpp \
                    common/cwchar.c \
                    common/wintz.c \
                    common/mutex.cpp \
                    common/dtintrv.cpp \
                    common/ucnvsel.cpp \
                    common/propsvec.c \
                    common/ulist.c \
                    common/uloc_tag.c \
                    common/icudataver.c \
                    common/icuplug.c \
                    common/listformatter.cpp

LOCAL_SHARED_LIBRARIES  := icudt51

include $(BUILD_SHARED_LIBRARY)

